parser:
  babel-eslint

parserOptions:
  ecmaVersion: 2019
  sourceType: module

env:
  es6: true
  browser: true
  node: true

plugins:
  - svelte3

overrides:
  - files:
    - "**/*.svelte"
    processor: svelte3/svelte3

extends:
  - eslint:recommended

rules:
  object-curly-spacing: 
    - error
    - always
  semi:
    - error
    - never
  quotes:
    - error
    - single
  comma-dangle:
    - error
    - only-multiline
  curly:
    - warn
    - multi
  no-multi-spaces:
    - error

  array-bracket-spacing:
    - error