language: node_js
node_js: 10
group: stable
dist: xenial
os: linux
sudo: required

services:
  - docker

before_install:
  - echo pass

install:
  - echo pass

script: 
  - if [[ $TRAVIS_BRANCH == "master" ]]; then TARGET_TAG="latest"; else TARGET_TAG="dev"; fi
  - docker build -t ${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$AWS_ECR_REPO:$TARGET_TAG .

before_deploy:
  - pip install awscli --upgrade --user
  - eval $(aws ecr get-login --registry-ids ${AWS_REGISTRY_ID} --region ${AWS_REGION} --no-include-email)

deploy:
  - provider: script
    script: |-
      docker push ${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$AWS_ECR_REPO:dev
    skip_cleanup: true
    on:
      branch: development
  - provider: script
    script: |-
      docker push ${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$AWS_ECR_REPO:latest
    skip_cleanup: true
    on:
      branch: master

