version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/freedomhkg-timeline/
hooks:
  BeforeInstall:
    - location: scripts/codedeploy/install.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/codedeploy/stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/codedeploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/codedeploy/validate_service.sh
      timeout: 180
      runas: root
