version: "3.4"
services:
  # arangodb-instance:
  #   image: arangodb/arangodb
  #   environment:
  #     - ARANGO_NO_AUTH=1
  #   ports:
  #     - 8529:8529
  #   command: --rocksdb.total-write-buffer-size 157286400

  # timeline-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: timeline-app
  #   container_name: timeline-app
  #   environment:
  #     - NODE_ENV=production
  #   links:
  #     - arangodb-instance:arangodb
  #   ports: 
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/src/app
  #     # - node_modules:/usr/src/app/node_modules
